# Generated by Django 5.2.10 on 2026-02-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_pettycash'),
        ('accounting', '0009_exchangerate'),
    ]

    operations = [
    ]
