# Generated by Django 5.2.10 on 2026-01-21 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_inventorymovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_reserved',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
