# Generated by Django 5.2.10 on 2026-01-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_stock_reserved'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_horizontal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_mayorista',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='price_moderno',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
