# Generated by Django 5.2.10 on 2026-01-29 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_base_salary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesGPSLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Latitud')),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Longitud')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Fecha y Hora')),
                ('is_active', models.BooleanField(default=True, verbose_name='GPS Activo')),
                ('seller', models.OneToOneField(limit_choices_to={'role': 'VENTAS'}, on_delete=django.db.models.deletion.CASCADE, related_name='gps_location', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Ubicación GPS Vendedor',
                'verbose_name_plural': 'Ubicaciones GPS Vendedores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
