# Generated by Django 5.2.10 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_alter_deliverybatch_distributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='actual_arrival_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Llegada'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='actual_departure_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora Real de Salida'),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='estimated_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora Estimada'),
        ),
    ]
