# Generated by Django 5.2.10 on 2026-01-18 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_remove_product_price_product_purchase_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('MAYORISTA', 'Mayorista'), ('SUPERMERCADO', 'Supermercado'), ('HORIZONTAL', 'Horizontal')], max_length=20)),
                ('margin_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category')),
            ],
            options={
                'unique_together': {('category', 'sale_type')},
            },
        ),
    ]
