# Generated by Django 5.2.10 on 2026-01-22 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_remove_payrollpayment_employee_payrollpayment_user'),
        ('sales', '0007_presale_reprogram_reason_presale_scheduled_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountReceivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('remaining_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Abono Parcial'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='sales.client')),
                ('pre_sale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_receivable', to='sales.presale')),
            ],
        ),
    ]
