# Generated by Django 5.2.10 on 2026-01-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_presale_presaleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presale',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado a repartidor'), ('CONFIRMADO', 'Confirmado/Vendido'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
