# Generated by Django 5.2.10 on 2026-01-21 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_presale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='reprogram_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motivo de Reprogramación'),
        ),
        migrations.AddField(
            model_name='presale',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Programada'),
        ),
    ]
