# Generated by Django 5.2.10 on 2026-01-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_image',
            field=models.ImageField(blank=True, null=True, upload_to='clients/business_pics/'),
        ),
    ]
