# Generated by Django 5.2.10 on 2026-01-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_presale_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='presale',
            name='has_pending_returns',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='presaleitem',
            name='returned_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
