# Generated by Django 5.2.10 on 2026-01-21 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_presale_has_pending_returns_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presale',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ASIGNADO', 'Asignado a repartidor'), ('CONFIRMADO', 'Confirmado/Vendido'), ('REPROGRAMADO', 'Reprogramado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
